# Generated by Django 5.0.3 on 2024-03-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(upload_to='aaplication/resume'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('applicant', 'applicant'), ('recruiter', 'recruiter')], max_length=20, verbose_name='role'),
        ),
    ]
